### ISSUE TITLE
running on custom dataset

### ISSUE THREAD

**Issue by andreaceruti** [ahrnbom/sorts#3]
Is it possible to run the algorithm on a custom dataset?
I already generate the detections and mask for each object instance using Mask RCNN.
Currently I am tracking bounding boxes using SORT, then I am trying to reproduce the masks in tracked bounding boxes for visualization.
I am not an expert but I think this is somehow the equivalent when doing instance segmentation, isn't it? 
So i would like to know how should I do for running the algorithm on my custom detections.

**Comment by ahrnbom** [comment]
Yes, it is absolutely possible to run the SORTS algorithm on any dataset. Have you looked at `demo.py`? It is a script included here for running SORTS on any video with people walking in them. 

If you want to re-use your existing Mask R-CNN instance segmentations, you would need to change the script to read your own detections from somewhere, instead of the default behaviour which is to run Mask R-CNN as part of the script.

If you have any further questions, you can ask them here and I will try to help you. Otherwise, if you feel this is sufficient guidance, feel free to close this issue.

**Comment by andreaceruti** [comment]
@ahrnbom Sorry for the late reply.
I have been able to rearrange SORTS in my custom environment without ReID and succesfully use the SORTS class on my detections for every video frame. 
When i try to run the demo inside the singularity bash I get this error 
> ModuleNotFoundError: No module named 'reid_files.model'

Since you put them in your gitignore file. So where can I get those weights you use for your model?


Then I have another question. I would like to give to SORTS my detections as before, but I would like to use also the ReID class to limit the id switching problem. Since for obtaining the detections I already use a MaskRCNN model, can I use the weights of my trained network for the ReID part? Or what should I have to extract from these weights?

**Comment by ahrnbom** [comment]
Hi! It seems I forgot to include some instructions for how to get those files. You can download them from here: https://lunduniversityo365-my.sharepoint.com/:u:/g/personal/ma7467ah_lu_se/EVwOThgpFZpCqW9SBRjP1CYB89TseqgvLL-tdc5SJJOeIA?e=tXv6I9

I will also update the readme shortly.

If you want to re-use Mask R-CNN weights to perform ReID, you will have to implement that yourself, because that's not how SORTS work.

I hope this answers your question. If so, feel free to close this issue.
